[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "databricks-acl-framework"
version = "0.1.0"
description = "A YAML-driven ACL provisioning and Schema Tagging framework for Databricks"
authors = [{ name = "Nivethan Venkatachalam", email = "nivethan.venkatachalam@diggibyte.com" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = ["PyYAML", "pyspark", "pytest"]